kubectl delete -f stolon-proxy-service.yaml
kubectl delete -f stolon-proxy.yaml
kubectl delete -f stolon-keeper.yaml
kubectl delete -f stolon-sentinel.yaml
kubectl delete -f ag_local-02.yaml
kubectl delete -f ag_local-01.yaml
kubectl delete -f secret.yaml
kubectl delete -f 00-default-admin-access.yaml
kubectl delete -f role-binding.yaml
kubectl delete -f role.yaml
